### ISSUE TITLE
Duplicated code blocks

### ISSUE THREAD

**Issue by altescape** [eFrane/vuepress-plugin-mermaidjs#92] opened 2022-01-10 12:11 UTC
Hi, I'm seeing a bug where duplicated code blocks are appearing when there is no space before the block in the markdown. It's easily remedied by adding a new line before the code block, but thought it was a bit odd. 

I removed your plugin and the duplicates in my example disappear, so it looks like something weird with the plugin perhaps or more likely the markdown rendering in Mermaid itself.

Please see example repo [here](https://github.com/altescape/vuepress-bug/blob/main/docs/guide/README.md?plain=1#L3-L6) and [here](https://github.com/altescape/vuepress-bug/blob/main/docs/guide/README.md?plain=1#L8-L19)

Example rendering can be seen at https://vuepress-bug.onrender.com/guide/

**Comment by fuzi1996** [comment] 2022-01-26 05:48
I found a similar question with version 1.9.0

# Reproduction link

[<img src="https://c.staticblitz.com/assets/favicon-7453cf0c12d349fb64b7aa2b69cc69c026f083a27f139f0839b1f4948bed6811.png" width = "50" height = "50" alt="#" align=center />Edit on Stackblitz](https://stackblitz.com/edit/node-oop14j?file=docs/README.md)

**Comment by fuzi1996** [comment] 2022-01-27 09:30
I found it was caused by [@mbalex99/markdown-it-fence](https://github.com/mbalex99/markdown-it-fence)

# Reproduction link

[<img src="https://c.staticblitz.com/assets/favicon-7453cf0c12d349fb64b7aa2b69cc69c026f083a27f139f0839b1f4948bed6811.png" width = "30" height = "30" alt="#" align=center />Edit on Stackblitz](https://stackblitz.com/edit/mbalex99markdown-it-fence-bug?file=index.js)

**Comment by eFrane** [comment] 2022-01-30 11:37
Hm… maybe using markdown-it-fence wasn't the best of ideas. While it reduced the sloc, it seems to increase the maintenance load. I propose to solve this by moving back to having a built-in markdown-it plugin.

**Comment by eFrane** [comment] 2022-03-12 13:52
Fixed in v1.9.1, thanks @fuzi1996.

**Closed by eFrane** 2022-03-12 13:52 UTC
